# Generated by Django 4.2.4 on 2024-03-21 01:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_alter_product_countinstock_alter_product_rating'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='brand',
            new_name='categoria',
        ),
        migrations.RemoveField(
            model_name='product',
            name='category',
        ),
    ]
