# Generated by Django 4.2.4 on 2024-03-21 01:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_rename_brand_product_categoria_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='description',
            new_name='descripcion',
        ),
    ]
