# Generated by Django 4.2.4 on 2024-03-21 01:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_rename_description_product_descripcion'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='numReviews',
            new_name='numeroReseña',
        ),
    ]
