# Generated by Django 4.2.4 on 2024-03-21 01:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_rename_numreviews_product_numeroreseña'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderitem',
            old_name='price',
            new_name='precio',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='price',
            new_name='precio',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='countInStock',
            new_name='stock',
        ),
    ]
