# Generated by Django 4.2.4 on 2024-03-21 01:46

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('base', '0009_rename_price_orderitem_precio_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Product',
            new_name='Producto',
        ),
        migrations.RenameField(
            model_name='orderitem',
            old_name='product',
            new_name='producto',
        ),
        migrations.RenameField(
            model_name='review',
            old_name='product',
            new_name='producto',
        ),
    ]
