# Generated by Django 4.2.4 on 2024-05-05 15:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_rename_product_producto_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Direccion',
            fields=[
                ('direccion', models.CharField(blank=True, max_length=200, null=True)),
                ('ciudad', models.CharField(blank=True, max_length=200, null=True)),
                ('precioEnvio', models.PositiveIntegerField(blank=True, null=True)),
                ('_id', models.AutoField(editable=False, primary_key=True, serialize=False)),
            ],
        ),
        migrations.RemoveField(
            model_name='shippingaddress',
            name='order',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='deliveredAt',
            new_name='LiberadoFecha',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='createdAt',
            new_name='creado',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='isDelivered',
            new_name='liberado',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='paymentMethod',
            new_name='metodoPago',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='isPaid',
            new_name='pagado',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='paidAt',
            new_name='pagadoFecha',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='shippingPrice',
            new_name='precioEnvio',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='totalPrice',
            new_name='totalPrecio',
        ),
        migrations.DeleteModel(
            name='Review',
        ),
        migrations.DeleteModel(
            name='ShippingAddress',
        ),
        migrations.AddField(
            model_name='direccion',
            name='order',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.order'),
        ),
    ]
