# Generated by Django 4.2.4 on 2024-05-06 15:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0011_direccion_remove_shippingaddress_order_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='creado',
            new_name='createdAt',
        ),
    ]
