# Generated by Django 4.2.4 on 2024-05-14 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0012_rename_creado_order_createdat'),
    ]

    operations = [
        migrations.AddField(
            model_name='direccion',
            name='celular',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
