# Generated by Django 4.2.4 on 2024-06-03 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0013_direccion_celular'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='numeroReseña',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='rating',
        ),
        migrations.AlterField(
            model_name='producto',
            name='image',
            field=models.ImageField(blank=True, default='/imagen.jpg', null=True, upload_to=''),
        ),
    ]
